import type { Phrase } from "./phrases";

export const EXTRA_PHRASES: Record<string, Phrase[]> = {
  greetings: [
    { en: "Welcome", pl: "Witam", pronunciation: "VEE-tahm" },
    { en: "Long time no see", pl: "Dawno się nie widzieliśmy", pronunciation: "DAHV-noh sheh nyeh vee-JEH-leesh-mih" },
    { en: "Have a nice day", pl: "Miłego dnia", pronunciation: "mee-WEH-goh dnyah" },
    { en: "Take care", pl: "Trzymaj się", pronunciation: "TSHIH-may sheh" },
    { en: "I'm sorry", pl: "Przepraszam", pronunciation: "psheh-PRAH-shahm" },
    { en: "No problem", pl: "Nie ma problemu", pronunciation: "nyeh mah proh-BLEH-moo" },
    { en: "Of course", pl: "Oczywiście", pronunciation: "oh-chih-VEESH-cheh" },
    { en: "I agree", pl: "Zgadzam się", pronunciation: "ZGAH-dzahm sheh" },
  ],
  restaurant: [
    { en: "Waiter!", pl: "Kelner!", pronunciation: "KEL-ner" },
    { en: "I'm vegetarian", pl: "Jestem wegetarianinem", pronunciation: "YES-tem veh-geh-tah-ryah-NEE-nem" },
    { en: "Without sugar", pl: "Bez cukru", pronunciation: "bez TSOO-kroo" },
    { en: "Can I pay by card?", pl: "Czy mogę zapłacić kartą?", pronunciation: "chi MOH-geh zah-PWAH-cheech KAR-tohn" },
    { en: "It's too salty", pl: "Za słone", pronunciation: "zah SWOH-neh" },
    { en: "One more please", pl: "Jeszcze jedno proszę", pronunciation: "YESH-cheh YED-noh PROH-sheh" },
    { en: "To go", pl: "Na wynos", pronunciation: "nah VIH-nohs" },
    { en: "Tip", pl: "Napiwek", pronunciation: "nah-PEE-vek" },
  ],
  shopping: [
    { en: "Receipt", pl: "Paragon", pronunciation: "pah-RAH-gon" },
    { en: "Discount", pl: "Zniżka", pronunciation: "ZNEESH-kah" },
    { en: "Sale", pl: "Wyprzedaż", pronunciation: "vih-PSHEH-dahsh" },
    { en: "Size", pl: "Rozmiar", pronunciation: "ROZ-myahr" },
    { en: "Can I try this on?", pl: "Czy mogę to przymierzyć?", pronunciation: "chi MOH-geh toh pshih-MYEH-zhihch" },
    { en: "Too expensive", pl: "Za drogie", pronunciation: "zah DROH-gyeh" },
    { en: "Cheap", pl: "Tanie", pronunciation: "TAH-nyeh" },
    { en: "Bag", pl: "Torba", pronunciation: "TOR-bah" },
  ],
  transport: [
    { en: "How long does it take?", pl: "Ile to trwa?", pronunciation: "EE-leh toh trvah" },
    { en: "Next stop", pl: "Następny przystanek", pronunciation: "nahs-TEMP-nih pshih-STAH-nek" },
    { en: "Transfer", pl: "Przesiadka", pronunciation: "psheh-SHAHT-kah" },
    { en: "Return ticket", pl: "Bilet powrotny", pronunciation: "BEE-let poh-VROT-nih" },
    { en: "Platform", pl: "Peron", pronunciation: "PEH-ron" },
    { en: "Delay", pl: "Opóźnienie", pronunciation: "oh-POOZH-nyeh-nyeh" },
    { en: "Parking", pl: "Parking", pronunciation: "PAR-keeng" },
    { en: "Gas station", pl: "Stacja benzynowa", pronunciation: "STATS-yah ben-zih-NOH-vah" },
  ],
  emergency: [
    { en: "Fire!", pl: "Pożar!", pronunciation: "POH-zhahr" },
    { en: "Ambulance", pl: "Karetka", pronunciation: "kah-RET-kah" },
    { en: "I'm allergic to...", pl: "Jestem uczulony na...", pronunciation: "YES-tem oo-choo-LOH-nih nah" },
    { en: "It hurts here", pl: "Tu boli", pronunciation: "too BOH-lee" },
    { en: "I need medicine", pl: "Potrzebuję lekarstwo", pronunciation: "poh-TSHEH-boo-yeh leh-KAR-stvoh" },
    { en: "My phone was stolen", pl: "Ukradziono mi telefon", pronunciation: "oo-krah-JOH-noh mee teh-LEH-fon" },
    { en: "Where is the exit?", pl: "Gdzie jest wyjście?", pronunciation: "gdjeh yest VIY-shcheh" },
    { en: "I need to call someone", pl: "Muszę do kogoś zadzwonić", pronunciation: "MOO-sheh doh KOH-gosh zah-DZVOH-neech" },
  ],
  numbers: [
    { en: "Zero", pl: "Zero", pronunciation: "ZEH-roh" },
    { en: "Eleven", pl: "Jedenaście", pronunciation: "yeh-deh-NAHSH-cheh" },
    { en: "Twelve", pl: "Dwanaście", pronunciation: "dvah-NAHSH-cheh" },
    { en: "Thirty", pl: "Trzydzieści", pronunciation: "tshih-JESH-chee" },
    { en: "Forty", pl: "Czterdzieści", pronunciation: "chtehr-JESH-chee" },
    { en: "Sixty", pl: "Sześćdziesiąt", pronunciation: "sheshch-JEH-shownt" },
    { en: "Seventy", pl: "Siedemdziesiąt", pronunciation: "sheh-dem-JEH-shownt" },
    { en: "First", pl: "Pierwszy", pronunciation: "PYERV-shih" },
  ],
  daily: [
    { en: "Where is the bathroom?", pl: "Gdzie jest łazienka?", pronunciation: "gdjeh yest wah-ZHEN-kah" },
    { en: "I'm tired", pl: "Jestem zmęczony", pronunciation: "YES-tem zmeh-CHOH-nih" },
    { en: "I'm happy", pl: "Jestem szczęśliwy", pronunciation: "YES-tem shchen-SHLEE-vih" },
    { en: "I'm sad", pl: "Jestem smutny", pronunciation: "YES-tem SMOOT-nih" },
    { en: "I'm busy", pl: "Jestem zajęty", pronunciation: "YES-tem zah-YEN-tih" },
    { en: "Wait a moment", pl: "Chwileczkę", pronunciation: "hvee-LECH-keh" },
    { en: "Hurry up!", pl: "Pospiesz się!", pronunciation: "POH-spyesh sheh" },
    { en: "I don't care", pl: "Nie obchodzi mnie to", pronunciation: "nyeh ob-HOH-djee mnyeh toh" },
  ],
  slang: [
    { en: "This sucks", pl: "To jest do bani", pronunciation: "toh yest doh BAH-nyee" },
    { en: "I screwed up", pl: "Spieprzyłem", pronunciation: "spyeh-PSHIH-wem" },
    { en: "Hangover", pl: "Kac", pronunciation: "kahts" },
    { en: "Broke (no money)", pl: "Spłukany", pronunciation: "SPWOO-kah-nih" },
    { en: "Wasted / Drunk", pl: "Pijany", pronunciation: "pee-YAH-nih" },
    { en: "To hit on someone", pl: "Podrywać", pronunciation: "pod-RIH-vahch" },
    { en: "Gossip", pl: "Plotka", pronunciation: "PLOT-kah" },
    { en: "Lucky!", pl: "Farciarze!", pronunciation: "far-CHAH-zheh" },
  ],
  food: [
    { en: "Butter", pl: "Masło", pronunciation: "MAHS-woh" },
    { en: "Pepper", pl: "Pieprz", pronunciation: "pyepsh" },
    { en: "Potato", pl: "Ziemniak", pronunciation: "ZHEM-nyahk" },
    { en: "Tomato", pl: "Pomidor", pronunciation: "poh-MEE-dor" },
    { en: "Apple", pl: "Jabłko", pronunciation: "YAHB-wkoh" },
    { en: "Cake", pl: "Ciasto", pronunciation: "CHAHS-toh" },
    { en: "Vodka", pl: "Wódka", pronunciation: "VOOD-kah" },
    { en: "Pierogi", pl: "Pierogi", pronunciation: "pyeh-ROH-gee" },
  ],
  weather: [
    { en: "It's cloudy", pl: "Jest pochmurno", pronunciation: "yest poh-HMOOR-noh" },
    { en: "It's warm", pl: "Jest ciepło", pronunciation: "yest CHEP-woh" },
    { en: "Storm", pl: "Burza", pronunciation: "BOO-zhah" },
    { en: "Spring", pl: "Wiosna", pronunciation: "VYOS-nah" },
    { en: "Summer", pl: "Lato", pronunciation: "LAH-toh" },
    { en: "Autumn", pl: "Jesień", pronunciation: "YEH-shyen" },
    { en: "Winter", pl: "Zima", pronunciation: "ZEE-mah" },
    { en: "Afternoon", pl: "Popołudnie", pronunciation: "poh-poh-WOO-dnyeh" },
  ],
};
