export interface Phrase {
  en: string;
  pl: string;
  pronunciation: string;
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
  phrases: Phrase[];
}

export const CATEGORIES: Category[] = [
  {
    id: "greetings",
    name: "Greetings",
    emoji: "👋",
    phrases: [
      { en: "Hello", pl: "Cześć", pronunciation: "cheshch" },
      { en: "Good morning", pl: "Dzień dobry", pronunciation: "jen DOH-bri" },
      { en: "Good evening", pl: "Dobry wieczór", pronunciation: "DOH-bri VYEH-choor" },
      { en: "Goodbye", pl: "Do widzenia", pronunciation: "doh vee-DZEH-nyah" },
      { en: "See you later", pl: "Do zobaczenia", pronunciation: "doh zoh-bah-CHEH-nyah" },
      { en: "Good night", pl: "Dobranoc", pronunciation: "doh-BRAH-nots" },
      { en: "How are you?", pl: "Jak się masz?", pronunciation: "yahk sheh mahsh" },
      { en: "I'm fine, thanks", pl: "Dobrze, dziękuję", pronunciation: "DOH-bzheh jen-KOO-yeh" },
      { en: "What's your name?", pl: "Jak masz na imię?", pronunciation: "yahk mahsh nah EE-myeh" },
      { en: "My name is...", pl: "Mam na imię...", pronunciation: "mahm nah EE-myeh" },
      { en: "Nice to meet you", pl: "Miło mi cię poznać", pronunciation: "MEE-woh mee cheh POZ-nahch" },
      { en: "Please", pl: "Proszę", pronunciation: "PROH-sheh" },
      { en: "Thank you", pl: "Dziękuję", pronunciation: "jen-KOO-yeh" },
      { en: "You're welcome", pl: "Proszę bardzo", pronunciation: "PROH-sheh BAR-dzoh" },
      { en: "Excuse me", pl: "Przepraszam", pronunciation: "psheh-PRAH-shahm" },
    ],
  },
  {
    id: "restaurant",
    name: "Restaurant",
    emoji: "🍽️",
    phrases: [
      { en: "A table for two, please", pl: "Stolik dla dwóch osób, proszę", pronunciation: "STOH-leek dlah dvooh OH-soob PROH-sheh" },
      { en: "The menu, please", pl: "Menu, proszę", pronunciation: "MEH-noo PROH-sheh" },
      { en: "I would like...", pl: "Poproszę...", pronunciation: "poh-PROH-sheh" },
      { en: "Water", pl: "Woda", pronunciation: "VOH-dah" },
      { en: "Beer", pl: "Piwo", pronunciation: "PEE-voh" },
      { en: "Wine", pl: "Wino", pronunciation: "VEE-noh" },
      { en: "Coffee", pl: "Kawa", pronunciation: "KAH-vah" },
      { en: "The bill, please", pl: "Rachunek, proszę", pronunciation: "rah-HOO-nek PROH-sheh" },
      { en: "It's delicious", pl: "Pyszne", pronunciation: "PISH-neh" },
      { en: "Cheers!", pl: "Na zdrowie!", pronunciation: "nah ZDRO-vyeh" },
      { en: "I'm hungry", pl: "Jestem głodny", pronunciation: "YES-tem GWOD-ni" },
      { en: "I'm thirsty", pl: "Chce mi się pić", pronunciation: "htseh mee sheh peech" },
      { en: "Breakfast", pl: "Śniadanie", pronunciation: "shnya-DAH-nyeh" },
      { en: "Lunch", pl: "Obiad", pronunciation: "OH-byaht" },
      { en: "Dinner", pl: "Kolacja", pronunciation: "koh-LAHTS-yah" },
    ],
  },
  {
    id: "shopping",
    name: "Shopping",
    emoji: "🛍️",
    phrases: [
      { en: "How much does it cost?", pl: "Ile to kosztuje?", pronunciation: "EE-leh toh kosh-TOO-yeh" },
      { en: "It's too expensive", pl: "To za drogo", pronunciation: "toh zah DROH-goh" },
      { en: "I'll take it", pl: "Wezmę to", pronunciation: "VEZ-meh toh" },
      { en: "Do you have...?", pl: "Czy macie...?", pronunciation: "chi MAH-cheh" },
      { en: "I'm just looking", pl: "Tylko oglądam", pronunciation: "TIL-koh oh-GLON-dahm" },
      { en: "Where is the store?", pl: "Gdzie jest sklep?", pronunciation: "gdjeh yest sklep" },
      { en: "Open", pl: "Otwarte", pronunciation: "oht-VAR-teh" },
      { en: "Closed", pl: "Zamknięte", pronunciation: "zahm-KNYEH-teh" },
      { en: "Cash", pl: "Gotówka", pronunciation: "goh-TOOV-kah" },
      { en: "Card", pl: "Karta", pronunciation: "KAR-tah" },
    ],
  },
  {
    id: "transport",
    name: "Transport",
    emoji: "🚌",
    phrases: [
      { en: "Where is the bus stop?", pl: "Gdzie jest przystanek?", pronunciation: "gdjeh yest pshi-STAH-nek" },
      { en: "Train station", pl: "Dworzec kolejowy", pronunciation: "DVOH-zhets koh-leh-YOH-vi" },
      { en: "Airport", pl: "Lotnisko", pronunciation: "lot-NEES-koh" },
      { en: "Taxi", pl: "Taksówka", pronunciation: "tahk-SOOV-kah" },
      { en: "One ticket, please", pl: "Jeden bilet, proszę", pronunciation: "YEH-den BEE-let PROH-sheh" },
      { en: "Where is...?", pl: "Gdzie jest...?", pronunciation: "gdjeh yest" },
      { en: "Left", pl: "Lewo", pronunciation: "LEH-voh" },
      { en: "Right", pl: "Prawo", pronunciation: "PRAH-voh" },
      { en: "Straight ahead", pl: "Prosto", pronunciation: "PROH-stoh" },
      { en: "How do I get to...?", pl: "Jak dojść do...?", pronunciation: "yahk doyshch doh" },
    ],
  },
  {
    id: "emergency",
    name: "Emergency",
    emoji: "🚨",
    phrases: [
      { en: "Help!", pl: "Pomocy!", pronunciation: "poh-MOH-tsi" },
      { en: "Call the police", pl: "Zadzwoń na policję", pronunciation: "ZAH-dzvon nah poh-LEETS-yeh" },
      { en: "I need a doctor", pl: "Potrzebuję lekarza", pronunciation: "poh-TSHEH-boo-yeh leh-KAH-zhah" },
      { en: "Hospital", pl: "Szpital", pronunciation: "SHPEE-tahl" },
      { en: "Pharmacy", pl: "Apteka", pronunciation: "ahp-TEH-kah" },
      { en: "I'm lost", pl: "Zgubiłem się", pronunciation: "zgoo-BEE-wem sheh" },
      { en: "I don't understand", pl: "Nie rozumiem", pronunciation: "nyeh roh-ZOO-myem" },
      { en: "Do you speak English?", pl: "Czy mówisz po angielsku?", pronunciation: "chi MOO-veesh poh ahn-GYEL-skoo" },
      { en: "I don't speak Polish", pl: "Nie mówię po polsku", pronunciation: "nyeh MOO-vyeh poh POL-skoo" },
      { en: "Can you help me?", pl: "Czy możesz mi pomóc?", pronunciation: "chi MOH-zhesh mee POH-moots" },
    ],
  },
  {
    id: "numbers",
    name: "Numbers",
    emoji: "🔢",
    phrases: [
      { en: "One", pl: "Jeden", pronunciation: "YEH-den" },
      { en: "Two", pl: "Dwa", pronunciation: "dvah" },
      { en: "Three", pl: "Trzy", pronunciation: "tshi" },
      { en: "Four", pl: "Cztery", pronunciation: "CHTEH-ri" },
      { en: "Five", pl: "Pięć", pronunciation: "pyench" },
      { en: "Six", pl: "Sześć", pronunciation: "sheshch" },
      { en: "Seven", pl: "Siedem", pronunciation: "SHEH-dem" },
      { en: "Eight", pl: "Osiem", pronunciation: "OH-shem" },
      { en: "Nine", pl: "Dziewięć", pronunciation: "JEH-vyench" },
      { en: "Ten", pl: "Dziesięć", pronunciation: "JEH-shench" },
      { en: "Twenty", pl: "Dwadzieścia", pronunciation: "dvah-JESH-chah" },
      { en: "Fifty", pl: "Pięćdziesiąt", pronunciation: "pyench-JEH-shownt" },
      { en: "One hundred", pl: "Sto", pronunciation: "stoh" },
      { en: "One thousand", pl: "Tysiąc", pronunciation: "TI-showns" },
    ],
  },
  {
    id: "daily",
    name: "Daily Life",
    emoji: "☀️",
    phrases: [
      { en: "Yes", pl: "Tak", pronunciation: "tahk" },
      { en: "No", pl: "Nie", pronunciation: "nyeh" },
      { en: "Maybe", pl: "Może", pronunciation: "MOH-zheh" },
      { en: "I like it", pl: "Podoba mi się", pronunciation: "poh-DOH-bah mee sheh" },
      { en: "I don't like it", pl: "Nie podoba mi się", pronunciation: "nyeh poh-DOH-bah mee sheh" },
      { en: "What time is it?", pl: "Która godzina?", pronunciation: "KTOO-rah goh-JEE-nah" },
      { en: "Today", pl: "Dzisiaj", pronunciation: "JEE-shay" },
      { en: "Tomorrow", pl: "Jutro", pronunciation: "YOO-troh" },
      { en: "Yesterday", pl: "Wczoraj", pronunciation: "FCHOH-rai" },
      { en: "I love you", pl: "Kocham cię", pronunciation: "KOH-hahm cheh" },
      { en: "Friend", pl: "Przyjaciel", pronunciation: "pshi-YAH-chel" },
      { en: "Family", pl: "Rodzina", pronunciation: "roh-JEE-nah" },
      { en: "Work", pl: "Praca", pronunciation: "PRAH-tsah" },
      { en: "Home", pl: "Dom", pronunciation: "dohm" },
      { en: "Beautiful", pl: "Piękny", pronunciation: "PYENK-ni" },
    ],
  },
  {
    id: "slang",
    name: "Street Polish",
    emoji: "🔥",
    phrases: [
      { en: "Cool / Awesome", pl: "Spoko", pronunciation: "SPOH-koh" },
      { en: "No way!", pl: "Nie ma mowy!", pronunciation: "nyeh mah MOH-vi" },
      { en: "What's up?", pl: "Co słychać?", pronunciation: "tsoh SWIH-hahch" },
      { en: "Let's go!", pl: "Chodźmy!", pronunciation: "HODJ-mi" },
      { en: "I'm bored", pl: "Nudzi mi się", pronunciation: "NOO-djee mee sheh" },
      { en: "That's crazy", pl: "To szalone", pronunciation: "toh shah-LOH-neh" },
      { en: "Relax / Chill", pl: "Wyluzuj", pronunciation: "vi-LOO-zooy" },
      { en: "No problem", pl: "Nie ma sprawy", pronunciation: "nyeh mah SPRAH-vi" },
      { en: "It doesn't matter", pl: "Nieważne", pronunciation: "nyeh-VAZH-neh" },
      { en: "Great / Perfect", pl: "Super", pronunciation: "SOO-per" },
      { en: "Dude / Buddy", pl: "Ziomek", pronunciation: "ZYOH-mek" },
      { en: "Party", pl: "Impreza", pronunciation: "eem-PREH-zah" },
      { en: "Awesome / Great", pl: "Ekstra", pronunciation: "EKS-trah" },
      { en: "Seriously?", pl: "Serio?", pronunciation: "SEH-ryoh" },
      { en: "Whatever", pl: "Cokolwiek", pronunciation: "tsoh-KOL-vyek" },
      { en: "Shut up!", pl: "Zamknij się!", pronunciation: "ZAHM-kneey sheh" },
      { en: "I'm tired of this", pl: "Mam tego dość", pronunciation: "mahm TEH-goh doshch" },
    ],
  },
  {
    id: "food",
    name: "Food & Drinks",
    emoji: "🍕",
    phrases: [
      { en: "Bread", pl: "Chleb", pronunciation: "hlep" },
      { en: "Milk", pl: "Mleko", pronunciation: "MLEH-koh" },
      { en: "Meat", pl: "Mięso", pronunciation: "MYEHN-soh" },
      { en: "Chicken", pl: "Kurczak", pronunciation: "KOOR-chahk" },
      { en: "Fish", pl: "Ryba", pronunciation: "RIH-bah" },
      { en: "Rice", pl: "Ryż", pronunciation: "rihsh" },
      { en: "Soup", pl: "Zupa", pronunciation: "ZOO-pah" },
      { en: "Salad", pl: "Sałatka", pronunciation: "sah-WAHT-kah" },
      { en: "Cheese", pl: "Ser", pronunciation: "sehr" },
      { en: "Egg", pl: "Jajko", pronunciation: "YAY-koh" },
      { en: "Sugar", pl: "Cukier", pronunciation: "TSOO-kyer" },
      { en: "Salt", pl: "Sól", pronunciation: "sool" },
      { en: "Ice cream", pl: "Lody", pronunciation: "LOH-dih" },
      { en: "Tea", pl: "Herbata", pronunciation: "her-BAH-tah" },
      { en: "Juice", pl: "Sok", pronunciation: "sohk" },
    ],
  },
  {
    id: "weather",
    name: "Weather & Time",
    emoji: "🌤️",
    phrases: [
      { en: "What's the weather like?", pl: "Jaka jest pogoda?", pronunciation: "YAH-kah yest poh-GOH-dah" },
      { en: "It's sunny", pl: "Jest słonecznie", pronunciation: "yest swoh-NECH-nyeh" },
      { en: "It's raining", pl: "Pada deszcz", pronunciation: "PAH-dah deshch" },
      { en: "It's snowing", pl: "Pada śnieg", pronunciation: "PAH-dah shnyeg" },
      { en: "It's cold", pl: "Jest zimno", pronunciation: "yest ZHEEM-noh" },
      { en: "It's hot", pl: "Jest gorąco", pronunciation: "yest goh-ROHN-tsoh" },
      { en: "Wind", pl: "Wiatr", pronunciation: "vyahtr" },
      { en: "Monday", pl: "Poniedziałek", pronunciation: "poh-nyeh-JAH-wek" },
      { en: "Tuesday", pl: "Wtorek", pronunciation: "FTOH-rek" },
      { en: "Wednesday", pl: "Środa", pronunciation: "SHROH-dah" },
      { en: "Thursday", pl: "Czwartek", pronunciation: "CHVAR-tek" },
      { en: "Friday", pl: "Piątek", pronunciation: "PYOHN-tek" },
      { en: "Saturday", pl: "Sobota", pronunciation: "soh-BOH-tah" },
      { en: "Sunday", pl: "Niedziela", pronunciation: "nyeh-JEH-lah" },
      { en: "Morning", pl: "Rano", pronunciation: "RAH-noh" },
    ],
  },
];

// Merge extra phrases
import { EXTRA_PHRASES } from "./extra-phrases";
CATEGORIES.forEach(cat => {
  const extras = EXTRA_PHRASES[cat.id];
  if (extras) cat.phrases.push(...extras);
});
